# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloglist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=255)),
                ('description1', models.CharField(max_length=255)),
                ('content1', models.TextField()),
                ('published1', models.BooleanField(default=True)),
                ('created1', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
